targets:
  $default:
    builders:
      freezed:
        options:
          copy_with: false
          equal: false
          to_json: false
      json_serializable:
        options:
          create_to_json: false
