name: cenoyam
description: Certainly Not Yandex Music.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers:
  injectable:
  get_it:
  provider:
  http:
  json_annotation:
  crypto:
  convert:
  flutter_bloc:
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator:
  json_serializable:
  freezed:


flutter:
  uses-material-design: true
