name: cenoyam
description: Certainly Not Yandex Music.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.17.0"

dependencies:
  audioplayers:
  bloc_concurrency:
  convert:
  cookie_jar:
  crypto:
  dio:
  dio_cookie_manager:
  flutter:
    sdk: flutter
  flutter_bloc:
  freezed_annotation:
  get_it:
  injectable:
  json_annotation:
  provider:

dev_dependencies:
  bloc_test:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  injectable_generator:
  json_serializable:
  mockingjay:
  mockito:
  mocktail:

dependency_overrides:
  analyzer: ">=4.2.0 <5.0.0"


flutter:
  uses-material-design: true
